font.base=font:DejaVu Sans,size:11
font.small=font:DejaVu Sans,size:11
font.comment=font:DejaVu Serif,size:11
font.code.comment.box=$(font.comment)
font.code.comment.line=$(font.comment)
font.code.comment.doc=$(font.comment)
font.code.comment.nested=$(font.comment)
font.text=font:DejaVu Serif,size:11
font.text.comment=font:Serif,size:11
font.embedded.base=font:Serif,size:11
font.embedded.comment=font:Serif,size:11
font.monospace=font:DejaVu Sans Mono,size:11
font.monospace.small=font:DejaVu Sans Mono,size:11
font.vbs=font:DejaVu Sans Mono,size:11

find.in.files.close.on.find=0
find.close.on.find=0