[mgr]
prepend_keymap = [
	{ on = "t",         		run = "shell --interactive",         		desc = "Run a shell command" },
	{ on = "T",        		run = "shell --block --interactive",	desc = "Run a shell command (block until finishes)" },
	
        { on = "+",			run = "create",					desc = "Create a file (ends with / for directories)" },
	{ on = "-",			run = "remove",					desc = "Trash selected files" },
	{ on = ["v", "v"],		run = "paste",					desc = "Paste files" },
	{ on = ["v",  "s"], 		run = "link", 					desc = "Symlink the absolute path of yanked files" },
	{ on = ["v", "h"],   		run = "hardlink",				desc = "Hardlink yanked files" },
	{ on = ["v", "o"],		run = "paste --before",				desc = "Paste files with overwrite" },
	{ on = "V",			run = "paste --before",				desc = "Paste files with overwrite" },
	
	{ on = "x",			run = "yank --cut",				desc = "Cut current character" },
        { on = [ "c", "c" ],		run = "yank",						desc = "Copy file" },
	{ on = "X",			run = "unyank",					desc = "Cancel cut" },
	{ on = "C",			run = "unyank",					desc = "Cancel copy" },
	
	{ on = [ "o", "n" ],		run = "open nano", 				desc = "Open in nano"},
	{ on = [ "o", "c" ],		run = "shell --quiet 'code %s'", 		desc = "Open in VS Code"},

	{ on = [ "c", "p" ],		run = "copy path",				desc = "Copy file URL" },
	
	{ on = ["t", "Left"],	run = "tab_switch -1 --relative",		desc = "Switch to previous tab" },
	{ on = ["t", "Right"],	run = "tab_switch 1 --relative",		desc = "Switch to next tab" },

	{ on = "C-f",         		run = "search --via=fd",             		desc = "Search files by name via fd" },
	{ on = "C-F",         		run = "search --via=rg",             		desc = "Search files by content via ripgrep" },
	
	{ on = ["l", "s"],   		run = "link",						desc = "Symlink the absolute path of yanked files" },
	{ on = ["l", "h"],   		run = "hardlink",					desc = "Hardlink yanked files" },
	

	{ on = [ "s", "a" ],		run = "sort alphabetical --reverse=no",                 			desc = "Sort alphabetically" },
	{ on = [ "s", "A" ],		run = "sort alphabetical --reverse=yes",					desc = "Sort alphabetically (reverse)" },
	{ on = [ "s", "s" ], 		run = [ "sort size --reverse=no", "linemode size" ],		desc = "Sort by size" },
	{ on = [ "s", "S" ],		run = [ "sort size --reverse=yes", "linemode size" ],		desc = "Sort by size (reverse)" },
	{ on = [ "s", "m" ],		run = [ "sort mtime --reverse=no", "linemode mtime" ],	desc = "Sort by modified time" },
	{ on = [ "s", "M" ],		run = [ "sort mtime --reverse=yes", "linemode mtime" ],	desc = "Sort by modified time (reverse)" },
	{ on = [ "s", "b" ],		run = [ "sort btime --reverse=no", "linemode btime" ],		desc = "Sort by birth time" },
	{ on = [ "s", "B" ],		run = [ "sort btime --reverse=yes", "linemode btime" ],	desc = "Sort by birth time (reverse)" },
	{ on = [ "s", "e" ],		run = "sort extension --reverse=no",					desc = "Sort by extension" },
	{ on = [ "s", "E" ],		run = "sort extension --reverse=yes",					desc = "Sort by extension (reverse)" },
	{ on = [ "s", "n" ],		run = "sort natural --reverse=no",						desc = "Sort naturally" },
	{ on = [ "s", "N" ],		run = "sort natural --reverse=yes",						desc = "Sort naturally (reverse)" },

]

[input]
prepend_keymap = [
    # Undo/Redo/Casefy
	{ on = "u",				run = [ "undo", "casefy lower" ], 					desc = "Undo, or lowercase if in visual mode" }
]
